### PR TITLE
Slime Ore

### PR DESCRIPTION
**Pull request by Azael-Snively**
This A Slime Ore a mineral who will serve for make armor in slime

### CODE REVIEW

**Review by halotroop2288 — CHANGES_REQUESTED** [review]
It appears you have just replaced stone with slime...
You may add *more* blocks, but don't replace existing ones.

**Comment by halotroop2288** [comment]
Cool. Now, add it to the world gen, or make a way to spawn it in, so it actually has some purpose.
(Spoiler alert, you're here too early, and that's not exactly easy to do.)

**Review by halotroop2288 — COMMENTED** [review]
Good. But that just preloads it so it can be loaded again faster later.

**Comment by Azael-Snively** [comment]
ok so what should i do

**Comment by halotroop2288** [comment]
Close the PR and wait for the actual core of the game to develop more.

**Pull request closed without merging**
